name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - kangdev

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: git
        run: |
          git --version
          git --version > gitversion
          git config --global user.email "1071318859@qq.com"
          git config --global user.name "1071318859"
          git add .
          git commit -m "update" -a
          git push

#      - name: Set up Go
#        uses: actions/setup-go@v4
#        with:
#          go-version: '1.20'

      - name: Build
        run: /bin/bash .github/workflows/test.sh


