name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - kangdev

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: ls | pwd | date

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

