name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - kangdev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: actions/checkout@v0.0.10

    - name: Build
      run: |
        pwd
        date
