name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - kangdev

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        env:
          USERNAME: "${{ secrets.USERNAME }}"
          FM_PASSWD: "aabbccdd"
        run: |
          env
          /bin/bash .github/workflows/build.sh

