name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - kangdev
      - 'releases/**'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        env:
          FM_MY_TOKEN: "${{ secrets.MY_TOKEN }}"
        run: |
          git tag -l
          #/bin/bash .github/workflows/build.sh

