name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - kangdev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: actions/checkout@kangdev
      run: |
        pwd
        date
        sh /home/runner/work/go-chainstorage-cli/go-chainstorage-cli/build.sh
